### ISSUE TITLE
NFG

### ISSUE THREAD

**Issue by joshuazick1** [joshuazick1/STu#1]
running script gives Traceback after adding Star Trek TV, does not happen with the movies
```
Traceback (most recent call last):
  File "cmcucp.py", line 97, in <module>
    playlist = Playlist.create(plex, plex_playlist, items)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/playlist.py", line 215, in create
    return cls._create(server, title, items)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/playlist.py", line 181, in _create
    uuid = items[0].section().uuid
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 519, in section
    return self._server.library.sectionByID(self.librarySectionID)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 396, in __getattribute__
    self.reload()
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 280, in reload
    self._loadData(data[0])
  File "/usr/local/lib/python3.7/dist-packages/plexapi/video.py", line 768, in _loadData
    self.media = self.findItems(data, media.Media)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 222, in findItems
    item = self._buildItemOrNone(elem, cls, initpath)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 93, in _buildItemOrNone
    return self._buildItem(elem, cls, initpath)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 78, in _buildItem
    return cls(self._server, elem, initpath, parent=self)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 51, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/media.py", line 65, in _loadData
    self.parts = self.findItems(data, MediaPart)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 222, in findItems
    item = self._buildItemOrNone(elem, cls, initpath)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 93, in _buildItemOrNone
    return self._buildItem(elem, cls, initpath)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 78, in _buildItem
    return cls(self._server, elem, initpath, parent=self)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 51, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/media.py", line 148, in _loadData
    self.streams = self._buildStreams(data)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/media.py", line 156, in _buildStreams
    items = self.findItems(data, cls, streamType=cls.STREAMTYPE)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 222, in findItems
    item = self._buildItemOrNone(elem, cls, initpath)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 93, in _buildItemOrNone
    return self._buildItem(elem, cls, initpath)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 78, in _buildItem
    return cls(self._server, elem, initpath, parent=self)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 51, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/media.py", line 373, in _loadData
    if self._isChildOf(etag='Track'):
  File "/usr/local/lib/python3.7/dist-packages/plexapi/base.py", line 124, in _isChildOf
    if obj._checkAttrs(obj._data, **kwargs):
AttributeError: 'NoneType' object has no attribute '_checkAttrs'
```

**Comment by joshuazick1** [comment]
Correction, this only happens when a movie is not first in the order
